services:
  postgres:
    container_name: annapoorna-postgres-sql
    hostname: postgres-sql
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres-password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: annapoorna
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - annapoorna
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - 5050:80
    networks:
      - annapoorna
    restart: unless-stopped
    depends_on:
      - postgres

  mail-dev:
    container_name: mail-dev
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
    networks:
      - annapoorna
    restart: unless-stopped

networks:
  annapoorna:
    driver: bridge

volumes:
  postgres:
    driver: local
  pgadmin:
    driver: local
