spring:
  application:
    name: annapoorna-backend
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 60MB
  devtools:
    restart:
      enabled: false
